# This workflow will install backend's requirements and run tests

name: Build MultiEd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: sudo apt update && sudo apt install qt6-base-dev libsdl2-dev libxmp-dev -y

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests

    - name: Run Setup Build Script
      run: python .github/workflow_scripts/setup_build.py linux

    - name: Run CMake
      run: |
        cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -S . -B ./cmake-build-debug-clang
        cmake --build ./cmake-build-debug-clang --target QT6Shared
        cmake --build ./cmake-build-debug-clang --target MultiEd

    - uses: actions/upload-artifact@v4
      with:
        name: MultiEd-linux-bin
        path: libs/OldUnrealSDK/System64/MultiEd-bin

#  windows:
#    runs-on: windows-latest
#
#    steps:
#    - uses: actions/checkout@v4
#
#    - run: choco install qt6-base-dev
#
#    - name: Set up Python
#      uses: actions/setup-python@v5
#      with:
#        python-version: '3.11'
#        cache: 'pip'
#
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        python -m pip install requests
#
#
#    - name: Run Setup Build Script
#      run: python .github/workflow_scripts/setup_build.py linux
#
#    - uses: actions/upload-artifact@v4
#      with:
#        name: windows-app
#        path: dist/app